#The falco rule "Get info about open windows" is designed to detect attempts to get information 
#about open application windows by monitoring specific commands such as "xwininfo", "wmctrl", "xprop",
#"xlsclients", "xdotool", "xrestop", "xwininfo", "xdpyinfo", "glxinfo", "xrandr", "xset", "xdriinfo", "xhost", "xev", "xdotool", and "xsetroot".
#https://attack.mitre.org/techniques/T1010/
#Mitre Discovery: application window discovery subscenario 
 
- rule: Get Information About Open Application Windows
  desc: Detects attempts to get information about open application windows
  condition: > 
    proc.name in ("xwininfo", "wmctrl", "xprop", "xlsclients", "xdotool", "xrestop", "xwininfo", "xdpyinfo", "glxinfo", "xrandr", "xset", "xdriinfo", "xhost", "xev", "xdotool", "xsetroot")
  enabled: true
  output: "Get info about open windows in system detected (proc.cmdline=%proc.cmdline connection=%fd.name user.name=%user.name user.loginuid=%user.loginuid container.id=%container.id evt.type=%evt.type     evt.res=%evt.res proc.pid=%proc.pid proc.cwd=%proc.cwd proc.ppid=%proc.ppid proc.pcmdline=%proc.pcmdline proc.sid=%proc.sid proc.exepath=%proc.exepath user.uid=%user.uid user.loginname=%user.loginname group.gid=%group.gid group.name=%group.name container.name=%container.name image=%container.image.repository)"
  priority: WARNING
  tags: [host, container, process, mitre_discovery, application_window_discovery, T1010]
